### ISSUE TITLE
Realtime Client: Long running connections

### ISSUE THREAD

**Issue by geberl** [reubenmiller/go-c8y#2]
My subscription to `/measurements/*` works perfectly fine for **2 hours** (to the second), then nothing gets transmitted for another hour (but no error occurs), after another hour I get cut off.

I only got around it by re-initializing the `client` each hour. A `UnsubscribeAll` followed by re-subscribing resulted in duplicate messages appearing in the channel. I might have done that wrong though.

How you handle long running connections of the realtime client?

**Comment by reubenmiller** [comment]
I'll have to investigate this, it looks to be two separate problems:

1. Long running realtime subscriptions are unstable (maybe auto-reconnect logic is required here)
2. `UnsubscribeAll` does not properly unsubscribe and results in duplicate subscriptions

I'll have to manually test what happens on the c8y side with long running realtime clients, and handle this scenario accordingly.

**Comment by geberl** [comment]
To 1.) I wouldn’t say it’s unstable, it behaves very predictable way. It almost looks like a feature of the Bayeux protocol to me. Maybe the data you send as ‘advice’ during the handshake (16h session length, 0s between reconnects) is ignored/altered by the server? The response should contain the actual connection attributes.

**Comment by reubenmiller** [comment]
Yeah I am probably just missing some kind of watchdog/handshake, I'll have to look up that part of the Bayeux spec.

Though I managed to fix the duplicate subscription problem, I tagged a new temp version v0.6.0-rc.1 (commit 02a9587) that you can try out in the meantime. So just update your go.mod file with "v0.6.0-rc.1" and let me know if that solves Problem 2.

**Comment by reubenmiller** [comment]
I found the source of the problem. The /meta/connect wasn't been sent to the server. I tested it on my machine and it keeps on receiving subscriptions after the 2 hours mark, and I can see the request from the server on the /meta/connect channel every 90 minutes (as specified in the advice from the server (i.e. every 5400000 ms).

I still need to write some additional tests for this, but I have tagged the commit with version "v0.6.0-rc.2" so you can test it for yourself.

**Comment by reubenmiller** [comment]
Sorry I just noticed I had a linting issue, I have tagged a new version v0.6.0-rc.3, but I will wait to see if it goes through the ci tests ok.

**Comment by geberl** [comment]
Nice. Testing now, will get back to you in some hours.

**Comment by reubenmiller** [comment]
Thanks for the information. Yeah I haven't added a proper checking for the reconnect advice received on the Bayeux reconnect logic.

I believe the sequence should be:

1. send handshake to server
2. recv handshake response from server
  -> If contains advice.reconnect "handshake, "then send handshake again (maybe with back-off algorithm)?
  ->else send normal /meta/connect heartbeat

I'm also refactoring the realtime client a bit to be more synchronous when using the .Connect() and .Subscribe() so that the function will only return if it receives a response from the server (or times out).

I'll work on it over the next few days.

**Comment by geberl** [comment]
Hey. Any news concerning this issue?
I might be able to contribute some of my time if you want.

**Comment by reubenmiller** [comment]
@geberl try out v0.6.0. It should resolve the issue now. If it doesn't then just reopen this issue.

**Comment by geberl** [comment]
Issue is indeed resolved. An automatic reconnect seems to happen for me every 2h50min.

Thanks!
