### ISSUE TITLE
Installer throws command override warning

### ISSUE THREAD

**Issue by EricSand** [reubenmiller/go-c8y#5]
When trying to install with ` Install-Module PSc8y -Repository PSGallery -AllowPrerelease
` the following error appears: 
`Line |
9685 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The following commands are already available on this
     | system:'Get-Event,New-Event,Remove-Event,Test-Json'. This module 'PSc8y' may override the existing
     | commands. If you still want to install this module 'PSc8y', use -AllowClobber parameter.`

Installing with `Install-Module PSc8y -Repository PSGallery -AllowPrerelease -AllowClobber` works fine.

Environment:
PS Version: 7.0.0 (fresh install)
Win 10 x64 Version 1909 (R. 18363.778)

**Comment by reubenmiller** [comment]
@EricSand This is something that will go away once a module prefix is added PSc8y modules. This will ensure that it does not conflict with existing powershell cmdlets (like. New-Event, Get-Event etc.).

When using a module prefix of "c8y", then all of the commands would get a "c8y" added after the hypen,

* New-C8yEvent
* Get-C8yEvent

The only downside is that it means more typing when entering a cmdlet...

**Comment by reubenmiller** [comment]
Closing issue as the go-c8y-cli and PSc8y project has been moved to a separate project which focuses on the cli tool. https://github.com/reubenmiller/go-c8y-cli.
